# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k6YllTwK-5Sf7d5tPh23zeRnXLXC5rcx
"""

#reverse a string
s=input().lower()
s1=s[::-1]
print(s1)